### ISSUE TITLE
Slider with multiple handles fires Set event twice when setting only one handle

### ISSUE THREAD

**Issue by thomhos** [leongersen/noUiSlider#579]
When I set one handle as such: 

slider.noUiSlider.set([null, 15]);

The 'set' event is still being fired two times because there are two handles. It seems to me that it should fire when I set two actual values, and not one 'valid' value as I do now.

Any way that I can trigger only one event when using this set method, or is there another way to only set one handle on a click?

**Comment by johndubya** [comment]
It seems the range slider is _always_ firing two `set` events when calling the `.set()` function, regardless what the new values are. Interestingly, this does not seem to be the case with version 7. In version 7, you could change the value of the underlying form input (e.g. `$("#price").val([0, 10000]);`), and it would only run the `set` event once.

The _reason_ it's running the `set` event twice seems to be because it wants to fire the event for each handle of the slider. I added a function to the `set` event on the documentation at https://refreshless.com/nouislider/events-callbacks/ , and it also fired twice upon clicking the ".set([ 5, 15 ])" button.

@leongersen, what can we look at to get the `set` event to only fire once, if we don't care which handle was targeted?

(this is a big deal for us, because we are doing some intense filtering on a data source every time the `set` event is called, so it is causing us problems that it is triggering filtering twice when calling `.set()`)

**Comment by johndubya** [comment]
@thomhos, we'll have to wait for @leongersen to confirm if this is the right way to do this or not, but it appears you can edit the nouislider.js file starting around line 1677 and remove the `for` statement that fires the `set` event on each handle, so it just looks like this:

    fireEvent('set', 0);

This fixed the issue of double triggering the `set` event on my end.

**Comment by leongersen** [comment]
It fires twice, once for each handle. The handleNumber argument can then be used to determine which handle was actually moved. It shouldn't fire on `.val()` if one of the arguments is `null`, but removing the for loop isn't the fix.

**Comment by leongersen** [comment]
I've just fixed this issue in version 8.3.0. The `set` event still fires for both handles (as spec'ed), but no longer does so for `null` (which was a bug!). Thanks for the report!

**Comment by nlundquist** [comment]
sorry for issue necromancy - but what was the rationale for continuing to fire `update` for handles that have `null` in the values passed to `.set()`?

**Comment by sergserg** [comment]
> It fires twice, once for each handle. The handleNumber argument can then be used to determine which handle was actually moved. It shouldn't fire on `.val()` if one of the arguments is `null`, but removing the for loop isn't the fix.

I still do not understand whether they gave a solution to the problem on this topic or not.

i solved this problem in a funny and weird way:

my_slider.noUiSlider.on('end', function () {
    my_slider.noUiSlider.set([null, null]);
    //Further, any code required for the 'end' event
   ...
   ...
   ...
});

**Comment by sergserg** [comment]
Code "my_slider.noUiSlider.set ([null, null]);" you can also insert it into the "Start" event and into the "Set" event, but I inserted it into the "End" event so that the user would not feel a delay in the start of the handle movement due to the "set" command being executed
