### ISSUE TITLE
Serious bug when using multiple sliders on chrome  (v 51.0.2704.84) 

### ISSUE THREAD

**Issue by eran-correlor** [leongersen/noUiSlider#805]
Hi Leon, First I like to embrace the hard work your put on this project, it is awesome and exactly what I was looking for,
Unfortunately I found a serious bug that I cannot resolve, When I try to put multiple sliders (could be only two) so when moving the handlers on the second slider - it interrupts the handlers the first one..
I was trying for hours to address this bug inside your code but without success..
Please let me know if you're familiar with this bug and have any idea how to solve it,
Just open it on chrome (v 51) and see that the bug occurs also on your demo page as well (https://refreshless.com/nouislider/).
I will be happy for any idea you can give why it happens so I can fix it myself.....
Thanks and all best,Eran

**Comment by eran-correlor** [comment]
For Leon - I pulled the previous version 9.2.0 and the bug **doesn't occur**, so it has something to do with the diffs between these vers.

**Comment by leongersen** [comment]
I'm out on a long term road trip and don't have access to any development
machine, so I'm sorry to say I can't help you work on this directly. One
thing you could try is removing the 'focusable' attribute.

**Comment by QuentinRoy** [comment]
Do you mean you are trying to move two handles at the same time? If so, by default the library does not support it. You may want to activate the new `multitouch` option.

**Comment by fwaadeland** [comment]
Has there been any progress on this?
I think I have the same issue (in Chrome only, currently @ Version 60.0.3112.113 (Official Build) (64-bit) OSX Sierra 10.12.5). 

Just installed the slider in my Angular 2 project yesterday and if I click the handle it will never stop tracking the mouse movement on any mousedown event in the window. At least the "set", "change" and "end" triggers continue to fire on any mouse movement inside window even after mouseup. If I click anywhere on the page after this, all the sliders that I have clicked on the handle, will sync up with the x position of the mouse. It is possible to set the slider by clicking anywhere that is not on the handle and it will work fine though.

**Comment by QuentinRoy** [comment]
Are you using the last version? If so, do you observing the same behavior with 10.0?

**Comment by fwaadeland** [comment]
Was using 10.1.0. Also tried 10.0.0. Just downgraded to 9.2.0 and here it works fine!

**Comment by fwaadeland** [comment]
I also noticed that in v10.x the handle gets this focused border styling when clicking on it, but that may or may not be relevant. Just an observation, does not happen in 9.2.0.

**Comment by QuentinRoy** [comment]
I still do not exactly understand the issue. Is this something you noticed on the official webpage as well? Can you precisely describe the actions to perform to reproduce the bug and what behavior you would expect instead?

**Comment by fwaadeland** [comment]
Once I click on a handle, it will do two things after the event:

1. Any movement on the mouse within the document will fire the noUiSlider triggers (at least 'change', 'set' and 'end', those were the ones I tried). So if I move the mouse 1px to the left they all triggers.
2. Any mousedown event within the document will start syncing the handle's x position, with the mouse's x position (or y depending on the orientation) until the mouseup event. 

This will add up for every time I click a handle (even if i click the same handle again) and never stop until I use the browser refresh. So when I click on the next handle, they both do this and so on.

Not an issue on https://refreshless.com/nouislider/. I also tried to recreate the issue in Codepen with no success. 

For reference, tested 10.1.0 and 10.0.0 in my project on Safari and it worked fine, only Chrome that is an issue.

I'll try to reproduce again later.

**Comment by QuentinRoy** [comment]
Hm. Not sure that's related to @eran-correlor problem. Could it be a problem with Angular 2 and nouislider fighting with each others?

**Comment by fwaadeland** [comment]
I am starting to think that might be the problem aswell. Should I create a new issue on it?

**Comment by senor-christo** [comment]
I am seeing the same thing on a page that has no js frontend framework applied to it, in chrome only (newest version) If we have multiple sliders on a page, and move the handle on one, and click the handle on say, the 5th one, it autoscrolls the page back to the first one. For clarity we are using the latest (10.X.X) version of nouislider. It appears to be registering a gotpointercapture event on the first slider that is interacted with, and then a lostpointercapture on any subsequent slider interaction, which then kicks off the scroll events.

**Comment by leongersen** [comment]
I think this issue might be the same as [this problem](https://github.com/leongersen/noUiSlider/issues/834#issuecomment-354520833).

**Comment by leongersen** [comment]
There's (I think) multiple problems discussed in this issue, but they should be fixed with noUiSlider 11 that I've just released. Thanks for reporting!

**Comment by bryevdv** [comment]
@leongersen We are still experiencing problems with use of noUiSlider in Bokeh, ever after updating to use version 11. You can visit this example:

https://bokeh.pydata.org/en/dev/docs/gallery/slider.html

with Chrome 51 on windows and see the strange behavior:

![screenflow](https://user-images.githubusercontent.com/1078448/35177420-db683452-fd44-11e7-9519-97d0c770870d.gif)

We do make a few customizations but I don't think it's anything that would cause this.

**Comment by leongersen** [comment]
@bryevdv I played with your page for a while before re-reading and noticing **5**1 rather than **6**1. Why are you trying a version that's over 1.5 years old, if you don't mind me asking?

**Comment by jburgy** [comment]
It's because of IT policies where I work so feel free to blame it on me. It works on iexplore but I wonder if this could creep up again.

**Comment by NickMcBurney** [comment]
Any updates on this? Using V11.0.3 and still seeing this issue with older versions of Chrome (same IT policy issues here)
